#!/bin/sh

unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS
export XKL_XMODMAP_DISABLE=1
export XDG_CURRENT_DESKTOP="XFCE"

# Синхронизация буфера обмена
autocutsel -fork
autocutsel -selection PRIMARY -fork
xfce4-clipman &

# Параметры ввода
xset r rate 200 40
setxkbmap us

xset s off          
xset s noblank        
xset -dpms           

pkill -9 xfce4-screensaver 2>/dev/null || true

# Запуск окружения
exec startxfce4
